stacktest: delimStack.o jbwd4HausP5.o
	g++ -o stacktest delimStack.o jbwd4HausP5.o

delimStack.o: delimStack.cpp delimStack.h
	g++ -g -c delimStack.cpp

jbwd4Hausp5.o: jbwd4HausP5.cpp delimStack.h
	g++ -g -c jbwd4HausP5.cpp